import type { AudioSpeakingEvaluationResult } from '@/lib/audioEvaluationTypes'
import { copy } from '@/lib/i18n'

type AudioFeedbackReportProps = { result: Extract<AudioSpeakingEvaluationResult, { status: 'completed' }> }

const criteria = [
  { key: 'fluencyAndCoherence' as const, label: copy.feedback.fluencyAndCoherence },
  { key: 'lexicalResource' as const, label: copy.feedback.lexicalResource },
  { key: 'grammaticalRangeAndAccuracy' as const, label: copy.feedback.grammaticalRangeAndAccuracy },
  { key: 'pronunciation' as const, label: copy.feedback.pronunciation },
]

export function AudioFeedbackReport({ result }: AudioFeedbackReportProps) {
  const confidence = result.confidence === 'low' ? copy.feedback.low : result.confidence === 'medium' ? copy.feedback.medium : copy.feedback.high
  const evidence = result.audioEvidence

  return <section className="mt-6 space-y-5" aria-label="录音客观反馈"><div className="rounded-2xl border border-brand-100 bg-brand-50 p-6 sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-brand-700">{copy.audioFirstFeedback.title}</p><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-slate-600">{copy.feedback.estimatedBand}</p><p className="mt-1 text-5xl font-bold tracking-tight text-ink">{result.estimatedBand.toFixed(1)}</p></div><p className="rounded-full bg-white px-3 py-1 text-sm font-semibold text-slate-700">{copy.feedback.confidence}：{confidence}</p></div><p className="mt-5 text-sm leading-6 text-slate-600">{result.disclaimer}</p></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{criteria.map(({ key, label }) => <div key={key} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold leading-5 text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold text-ink">{result.criteria[key].toFixed(1)}</p></div>)}</div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-ink">{copy.audioFirstFeedback.evidence}</h2><div className="mt-5 grid gap-4 lg:grid-cols-2"><article className="rounded-xl bg-slate-50 p-4"><h3 className="font-semibold text-ink">{copy.audioFirstFeedback.rawTranscript}</h3><p lang="en" className="mt-2 text-sm leading-6 text-slate-700">{evidence.rawTranscript}</p></article><article className="rounded-xl bg-slate-50 p-4"><h3 className="font-semibold text-ink">{copy.audioFirstFeedback.pauses}</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm leading-6 text-slate-700">{evidence.detectedPauses.length ? evidence.detectedPauses.map((item) => <li key={item}>{item}</li>) : <li>未检测到明显停顿。</li>}</ul></article><article className="rounded-xl bg-slate-50 p-4"><h3 className="font-semibold text-ink">{copy.audioFirstFeedback.hesitation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{evidence.hesitationAndRepetitionComment}</p></article><article className="rounded-xl bg-slate-50 p-4"><h3 className="font-semibold text-ink">{copy.audioFirstFeedback.speechRate}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{evidence.speechRateComment}</p></article><article className="rounded-xl bg-slate-50 p-4"><h3 className="font-semibold text-ink">{copy.audioFirstFeedback.pronunciation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{evidence.pronunciationComment}</p></article><article className="rounded-xl bg-slate-50 p-4"><h3 className="font-semibold text-ink">{copy.audioFirstFeedback.fluency}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{evidence.fluencyComment}</p><p className="mt-3 text-sm leading-6 text-slate-600"><span className="font-semibold">{copy.audioFirstFeedback.audioQuality}：</span>{evidence.audioQualityComment}</p></article></div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.summary}</h2><p className="mt-3 leading-7 text-slate-600">{result.summary}</p></div>
    <div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.strengths}</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-600">{result.strengths.map((item) => <li key={item}>• {item}</li>)}</ul></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.improvements}</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-600">{result.priorityImprovements.map((item) => <li key={item}>• {item}</li>)}</ul></div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.criteriaFeedback}</h2><div className="mt-5 grid gap-4 lg:grid-cols-2">{criteria.map(({ key, label }) => { const item = result.criteriaFeedback[key]; return <article key={key} className="rounded-xl bg-slate-50 p-4"><h3 className="font-semibold text-ink">{label}</h3><p className="mt-3 text-sm leading-6"><span className="font-semibold">优点：</span>{item.strength}</p><p className="mt-2 text-sm leading-6"><span className="font-semibold">改进：</span>{item.improvement}</p></article> })}</div></div>
    {result.corrections.length ? <div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.corrections}</h2><div className="mt-4 space-y-4">{result.corrections.map((item, index) => <article key={`${item.original}-${index}`} className="rounded-xl border border-slate-100 p-4 text-sm"><p>{copy.feedback.original}：<span lang="en">{item.original}</span></p><p className="mt-2 font-medium text-emerald-700">{copy.feedback.try}：<span lang="en">{item.suggested}</span></p><p className="mt-2 text-slate-600">{item.explanation}</p></article>)}</div></div> : null}
    <div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.betterAnswer}</h2><p lang="en" className="mt-4 whitespace-pre-line leading-7 text-slate-700">{result.betterAnswer.text}</p></div><div className="rounded-2xl border border-brand-100 bg-brand-50 p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.nextTask}</h2><p className="mt-3 leading-7 text-slate-700">{result.nextPracticeTask.instruction}</p></div>
    {result.qualityFlags.length ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><p className="font-semibold">录音质量提示</p><ul className="mt-2 list-disc space-y-1 pl-5">{result.qualityFlags.map((flag) => <li key={flag}>{flag}</li>)}</ul></div> : null}
  </section>
}
