import type { CriterionName, SpeakingEvaluationResult } from '@/lib/evaluationTypes'
import { copy } from '@/lib/i18n'

type SpeakingFeedbackReportProps = { result: Extract<SpeakingEvaluationResult, { status: 'completed' }> }

const criteria: Array<{ key: CriterionName; label: string }> = [
  { key: 'fluencyAndCoherence', label: copy.feedback.fluencyAndCoherence },
  { key: 'lexicalResource', label: copy.feedback.lexicalResource },
  { key: 'grammaticalRangeAndAccuracy', label: copy.feedback.grammaticalRangeAndAccuracy },
  { key: 'pronunciation', label: copy.feedback.pronunciation },
]

export function SpeakingFeedbackReport({ result }: SpeakingFeedbackReportProps) {
  const confidence = result.confidence === 'low' ? copy.feedback.low : result.confidence === 'medium' ? copy.feedback.medium : copy.feedback.high

  return <section className="mt-6 space-y-5" aria-label="AI 口语反馈"><div className="rounded-2xl border border-brand-100 bg-brand-50 p-6 sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-brand-700">{copy.feedback.report}</p><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-slate-600">{copy.feedback.estimatedBand}</p><p className="mt-1 text-5xl font-bold tracking-tight text-ink">{result.estimatedBand.toFixed(1)}</p></div><p className="rounded-full bg-white px-3 py-1 text-sm font-semibold text-slate-700">{copy.feedback.confidence}：{confidence}</p></div><p className="mt-5 text-sm leading-6 text-slate-600">{result.disclaimer}</p></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{criteria.map(({ key, label }) => <div key={key} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold leading-5 text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold text-ink">{result.criteria[key].toFixed(1)}</p></div>)}</div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.summary}</h2><p className="mt-3 leading-7 text-slate-600">{result.summary}</p></div>
    <div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.strengths}</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-600">{result.strengths.map((item) => <li key={item} className="flex gap-3"><span className="font-bold text-emerald-600">✓</span>{item}</li>)}</ul></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.improvements}</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-600">{result.priorityImprovements.map((item) => <li key={item} className="flex gap-3"><span className="font-bold text-brand-600">→</span>{item}</li>)}</ul></div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.criteriaFeedback}</h2><div className="mt-5 grid gap-4 lg:grid-cols-2">{criteria.map(({ key, label }) => { const feedback = result.criteriaFeedback[key]; return <article key={key} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><h3 className="font-semibold text-ink">{label}</h3>{feedback.assessmentConfidence ? <span className="text-xs font-semibold text-slate-500">{copy.feedback.confidence}：{feedback.assessmentConfidence === 'low' ? copy.feedback.low : feedback.assessmentConfidence === 'medium' ? copy.feedback.medium : copy.feedback.high}</span> : null}</div><p className="mt-3 text-sm leading-6 text-slate-600"><span className="font-semibold text-slate-700">优点：</span>{feedback.strength}</p><p className="mt-2 text-sm leading-6 text-slate-600"><span className="font-semibold text-slate-700">改进：</span>{feedback.improvement}</p>{feedback.evidence.length ? <ul className="mt-3 list-disc space-y-1 pl-5 text-sm leading-6 text-slate-500">{feedback.evidence.map((item) => <li key={item}>{item}</li>)}</ul> : null}</article> })}</div></div>
    {result.corrections.length ? <div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.corrections}</h2><div className="mt-4 space-y-4">{result.corrections.map((correction, index) => <article key={`${correction.original}-${index}`} className="rounded-xl border border-slate-100 p-4 text-sm"><p className="text-slate-500">{copy.feedback.original}：<span lang="en" className="text-slate-700">{correction.original}</span></p><p className="mt-2 font-medium text-emerald-700">{copy.feedback.try}：<span lang="en">{correction.suggested}</span></p><p className="mt-2 leading-6 text-slate-600">{correction.explanation}</p></article>)}</div></div> : null}
    <div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.betterAnswer}</h2><p className="mt-2 text-sm font-medium text-brand-700">{result.betterAnswer.level}</p><p lang="en" className="mt-4 whitespace-pre-line leading-7 text-slate-700">{result.betterAnswer.text}</p><ul className="mt-4 list-disc space-y-1 pl-5 text-sm leading-6 text-slate-500">{result.betterAnswer.notes.map((note) => <li key={note}>{note}</li>)}</ul></div>
    <div className="rounded-2xl border border-brand-100 bg-brand-50 p-6"><h2 className="text-lg font-semibold text-ink">{copy.feedback.nextTask}</h2><p className="mt-3 leading-7 text-slate-700">{result.nextPracticeTask.instruction}</p><p className="mt-3 text-sm font-semibold text-brand-700">{copy.common.focus}：{criteria.find((criterion) => criterion.key === result.nextPracticeTask.focusCriterion)?.label}</p></div>
    {result.qualityFlags.length ? <p className="text-sm text-slate-500">质量标记：{result.qualityFlags.join('、')}</p> : null}
  </section>
}
